auth-utils/config.js
auth-utils/grant-manager.js
connect/middleware/protect.js

Added Bearer only support to config and fix error in parse rawData when origin from BearerStore.

Add Bearer Only support

---

connect/index.js

Hi,
Please review if this bits are correct and applicable.
https://issues.jboss.org/browse/KEYCLOAK-2638
For the same example described on issue ^ this redirects without errors for login page.

Updating URLs for login and logout

---

README.md
package.json
test/keycloak-connect-test.js

before:
Statements   : 37.8% ( 93/246 )
Branches     : 16.48% ( 15/91 )
Functions    : 20% ( 10/50 )
Lines        : 37.8% ( 93/246 )
after:
Statements   : 54.88% ( 135/246 )
Branches     : 32.97% ( 30/91 )
Functions    : 42% ( 21/50 )
Lines        : 54.88% ( 135/246 )

coverage % increased and minor readme typo fix.

---

middleware/protect.js

Changed redirect URL to use originalUrl instead of url as it was stripping the baseUrl

Changed redirect URL to use originalUrl instead of url

---

index.js
package.json

Convert all `Q` promises to ES2015 native.
Found only one usage.

KEYCLOAK-3110

---

stores/cookie-store.js
stores/session-store.js

@lance @abstractj  @helio-frota mind taking a quick look.
For https://issues.jboss.org/browse/KEYCLOAK-3199
instead of adding the function keyword back in, i've made it more "functional" so its not as confusing where this comes from

remove this and make the store function functional

---

README.md

Adding dependency info badge for the project

---

Makefile
package.json

Modified files:
package.json
Makefile

Coverage quick fix.

---

.travis.yml
package.json

@sebastienblanc could you please review?

Update auth-utils dependency

---

index.js
test/unit/keycloak-object-test.js

@sebastienblanc could you please review?

[KEYCLOAK-4685] Doc Bug in Node.js Adapter doc - Keycloak() requires a config argument

---

test/fixtures/node-console/index.js
test/fixtures/node-console/views/index.html
test/fixtures/testrealm.json
test/keycloak-connect-web-spec.js
test/utils/webdriver.js

- Add a restricted endpoint per role
- Clean up of index page to look exactly the same as js-console
- Inclusion of the same users from the quickstarts to the realm
configuration
- Removal of unused functions
- Add support to selenium utility to provide path after host

Test case scenario for roles

---

test/keycloak-connect-web-spec.js
test/utils/config.js
test/utils/helper.js
test/utils/realm.js
test/utils/webdriver.js

- Removal of verbosity for the testsuite

Make the testsuite syntax shorter

---

test/keycloak-connect-web-spec.js
test/utils/webdriver.js

@abstractj Could I ask you for review? This is one of the changes we discussed.

KEYCLOAK-6464 Stabilize logout in tests

---

middleware/admin.js
middleware/auth-utils/grant-manager.js
middleware/auth-utils/token.js
test/fixtures/node-console/index.js
test/grant-manager-spec.js

@pedroigor because you're already familiar to this. Could you please review next week?

[KEYCLOAK-8076] Remove deprecation warning messages from Node.js adapter

---

product/pom.xml

Also update product pom's minor version to match product.json. It should be
kept in sync.

KEYCLOAK-7911 Include Final in product pom version

---

product/prod-arguments.json

This will allow dynamic alignment to versions suggested by DA

KEYCLOAK-8241 Switch dependencySource to BOMREST in prod-arguments

---

middleware/auth-utils/grant-manager.js

I am not sure whether you require keycloak issue for each PR in nodejs adapter. If yes let me know I will create one.

KEYCLOAK-10035 Align token error message with Java adapters

---

test/keycloak-connect-web-spec.js
test/utils/webdriver.js

KEYCLOAK-10282 Fix instabilities in nodejs tests

---

.travis.yml
package-lock.json
package.json
test/utils/webdriver.js

KEYCLOAK-10359 Run tests with chrome instead of phantomjs

---

product/pom.xml

KEYCLOAK-10430 Replace phantomjs with chromedriver for product build

---

package-lock.json
package.json

[KEYCLOAK-10656] Update Node.js adapter dependencies

---

.gitignore
package-lock.json
package.json
run-tests.sh

https://issues.jboss.org/browse/KEYCLOAK-10187
This commit introduces xUnit style reports for TAP (see the [project page](https://github.com/aghassemi/tap-xunit)). This should allow us to report failures in Jenkins UI.
Still to be done:

KEYCLOAK-10187 JUnit report style

---

keycloak.d.ts

StandardClaims is not defined yet.  So we need to remove the reference.

Remove "extends StandardClaims"

---

package-lock.json
package.json

@hmlnarik we might need to backport this to prod if we still have time. This won't affect the way how the adapter works, but people will have issues by running integration tests.

[KEYCLOAK-11016] Node.js build on Travis is broken due to chromedriver updates

---

product/pom.xml

KEYCLOAK-11007 Missing keycloak.js in Node.js adapter

---

.travis.yml

[KEYCLOAK-10998] Disable cache on Travis for Node.js adapter

---

package-lock.json
package.json

[KEYCLOAK-11267] Upgrade Node.js adapter development dependencies

---

package.json
product/pom.xml

Without this the keycloak.d.ts is not included in the packaged tarball.

KEYCLOAK-11885 Add keycloak.d.ts to "files" property

---

middleware/auth-utils/config.js
package-lock.json
scripts/start-server.sh

KEYCLOAK-12042 Fix doubled slash in realm urls

---

keycloak.d.ts

I've copied the `keycloak.d.ts` file directly into my TypeScript project while I wait for a new release that contains the types. However I've found a couple of minor issues which I've fixed in this PR.

fix: errors in typings

---

.travis.yml

[KEYCLOAK-12820] Update Travis to test the most recent Node.js releases

---

middleware/auth-utils/config.js
package-lock.json
test/keycloak-connect-web-spec.js

[KEYCLOAK-12428](https://issues.redhat.com/browse/KEYCLOAK-12428)
The Node.js adapter is broken when urls contain a forward slash by the end of the URL. For example: http://localhost:8080/auth///////
1. Follow the steps to reproduce described in the same Jira
2. Run make tests

[KEYCLOAK-12428] Extra '/' character in the client > OIDC Json installation file

---

package.json
product/pom.xml

KEYCLOAK-12951 Add run-tests.sh to RH-SSO dist

---

test/fixtures/auth-utils/nodejs-test-realm.json
test/fixtures/testrealm.json

KEYCLOAK-13389 Fix identity provider urls configuration

---

keycloak.d.ts

Added missing type definitions of functions that are exposed by the keycloak-connect module
Unfortunately nobody replied in the issue tracker if I could get assigned for this issue, but I decided to publish this PR anyways, because I want to fix this issue before keycloak-connect v9.0.1 is released.

KEYCLOAK-12771 Added missing type definitions

---

middleware/logout.js
test/keycloak-connect-rest-mixed-client-spec.js

PR for documentation is [here](https://github.com/keycloak/keycloak-documentation/pull/875)

KEYCLOAK-13289 logout can be called with redirect_url

---

scripts/start-server.sh

KEYCLOAK-14547: Make New Account Console the default

---

package-lock.json

[KEYCLOAK-15725] Update dependencies in package-lock.json

---

.travis.yml
keycloak.js
package-lock.json
package.json
test/fixtures/node-console/index.js
test/keycloak-connect-web-spec.js

I've reused the original JIRA ([KEYCLOAK-15859](https://issues.redhat.com/browse/KEYCLOAK-15859)) as it's not yet closed. Let me know if I should create a new JIRA just for this.

KEYCLOAK-16026 Add tests for cookie store

---

keycloak.d.ts

Add documentation for Keycloak.prototype.redirectToLogin()

KEYCLOAK-16071 Add redirectToLogin docs

---

test/keycloak-connect-rest-mixed-client-spec.js

The latest LTS released version of Node.js uses different messages.
JIRA: [KEYCLOAK-19703](https://issues.redhat.com/browse/KEYCLOAK-19703)
@abstractj @edewit Could you please take a look at it? Thank you

KEYCLOAK-19703 Cannot read property 'kid' of undefined

---

package.json

Update with the reference to the version of the keycloak-admin-client without breaking backward compatibility

---

CONTRIBUTING.md
README.md

Also replaces outdated links with updated versions.

Replace references to JIRA with Github Issues

---

package-lock.json
package.json

chore: use same LTS node versions as declared on CI

---

package-lock.json
package.json
test/grant-manager-spec.js

Remove the abandoned `jshint` package

---

get-version.sh
set-version.sh

Clean up old release code from Node.js adapter repo

---

middleware/auth-utils/grant-manager.js
middleware/auth-utils/rotation.js

Terminate request connection on error status code

---

.github/workflows/main.yml
README.md

Fix CI badge in readme

---

package-lock.json
package.json
test/utils/realm.mjs

Upgrade `@keycloak/keycloak-admin-client` to latest version

---

test/utils/webdriver.mjs

Wait for events to be visible in tests

---

package.json

Make chromedriver a dev dependency
