auth-utils/grant-manager.js
grant-manager.js and ensureFreshness method have:
````javascript
// GrantManager.prototype.ensureFreshness()
if ( options.protocol == 'https:' ) {
protocol = https;
} else {
protocol = http;
}
````
But options variable is not exists, solved by change opts variable's name to options
=> bug: var options in ensureFreshness() method not found because the name of the variable is opts.

auth-utils/grant-manager.js, connect/middleware/logout.js, connect/middleware/protect.js
In the connect/middleware/logout.js and connect/middleware/protect.js the protocol is hardcoded. I changed this to get from request and obtain the port from header.
=> Fix hardcoded protocol and port redirect

auth-utils/grant-manager.js
typeof is an operator, not a function. Because of this, the condition is never true, and the JSON never gets parsed, and this raises exceptions
=> Fix mistake on typeof

connect/index.js
This is a fix for a bug in master. In my use case at least it's causing a redirect loop because the grant-attacher fails to attach the grant even when the user is authenticated.
As far as I can tell rawData is always the value from grant.__raw, set in createGrant and is always JSON (or undefined). It needs to be deserialized to be able to check rawData.error.
=> FIX: deserialize stored token

index.js
disclaimer : I'm not a JS expert, fix could be nicer maybe. 
This extra check makes the nodejs adapter work when the application is configured as "bearer-only" , fix is inspired by this commit from the util project https://github.com/keycloak/keycloak-nodejs-auth-utils/commit/e4e8e98a051b46baf5247c7bd7d3e7c7c2275973 , not sure why it was not applied as well for this project at that time.
@abstractj @lholmquist it's all yours ... 
tested with KC 1.9.1
=> Check if the token is a string or an object before parsing

index.js, stores/session-store.js
`store.getId` isn't implemented in cookie store, leading to a crash when logging in. I'm not really sure what its use is anyway, so I figured I could probably just delete it...
=> Remove store.getId

middleware/protect.js
This fixes the following error if the express-session middleware is not in use.
```
TypeError: Cannot set property 'auth_redirect_uri' of undefined
at forceLogin (/home/n-code/api-demo/node_modules/keycloak-connect/middleware/protect.js:11:37)
at protect (/home/n-code/api-demo/node_modules/keycloak-connect/middleware/protect.js:44:7)
at Layer.handle [as handle_request] (/home/n-code/api-demo/node_modules/express/lib/router/layer.js:95:5)
at next (/home/n-code/api-demo/node_modules/express/lib/router/route.js:131:13)
```
=> Don't crash in forceLogin when session is unavailable

example/package.json, index.js
@lance @lholmquist could you please review when you get the chance?
Instructions to test:
1. git clone https://github.com/keycloak/keycloak && cd keycloak
2. mvn clean install -DskipTests=true && mvn -f testsuite/integration/pom.xml exec:java -Pkeycloak-server
3. Import the realm configuration from examples folder
4. run our example
=> [KEYCLOAK-3324] - Node.js adapter : ensure the initial OIDC authenticationRequest contains scope=openid

middleware/protect.js, test/keycloak-connect-test.js
Check if original request already contains a query string and append auth_callback=1 to existing query string if one exists; add query string otherwise. Fixes [KEYCLOAK-3384][0].
[0]: https://issues.jboss.org/browse/KEYCLOAK-3384
=> KEYCLOAK-3384: Fix login redirect URL generation

.gitignore, Makefile, package.json, test/keycloak-connect-test.js, test/unit/keycloak-object-test.js
We need to move unit tests related to
keycloak javascript object toanother
directory:
tests/unit/keycloak-object-test.js
This will make things more clear.
=> KEYCLOAK-3516 Better test organization.

index.js, test/unit/keycloak-object-test.js
:warning: This PR is linked with https://github.com/keycloak/keycloak-nodejs-auth-utils/pull/41 and integrations tests will probably fail on travis since it needs the changes of `keycloak-nodejs-auth-utils` . But locally and updating your package.json to use  https://github.com/keycloak/keycloak-nodejs-auth-utils/pull/41 as dependencies the tests should pass.
@abstractj Do you mind reviewing ?
=> KEYCLOAK-3871 : add key rotation support

package.json
For further releases keycloak-bot will automatically update `package.json` file with the latest release of auth-utils before the release and after will be switched to the development version back again.
=> Switch to development version of keycloak-auth-utils

.gitignore, index.js, middleware/auth-utils/grant-manager.js, test/fixtures/node-console/index.js, test/fixtures/templates/confidential-template.json, test/grant-manager-spec.js, test/keycloak-connect-rest-mixed-client-spec.js, test/utils/token.js
Fix regression causing service calls to clients not configured as bearer-only to fail.
This change makes Keycloak Connect behave similarly to Keycloak's Java adapters when a token is requested and but a refresh token is not present.
=> KEYCLOAK-5823 Fix service calls

index.js
This reverts commit 01cf8a63805d1bbef04e3b2524d5b7f2c5adf7be.
=> Revert "[KEYCLOAK-6171] Node.js adapter doesn't remove "session_state" from URL after login

middleware/auth-utils/grant-manager.js, test/grant-manager-spec.js
grant_type refresh_token throws 'invalid_client_credentials', when
client_id is not a part of openid-connect/token request
When token is renewed on POST request to
'/auth/realms/master/protocol/openid-connect/token', RHEL-SSO 7.1 throws
back error as below.
{"error":"unauthorized_client","error_description":"UNKNOWN_CLIENT:
Client was not identified by any client authenticator"}
This is fixed by adding client_id to the http request getting token
renewed.
=> [KEYCLOAK-6093] grant_type refresh_token throws 'invalid_client_credentials', when client_id is missing

product/pom.xml
The PR for KEYCLOAK-6909 (#121) was modified to put the new stuff in a
subdirectory. I omitted to check that the pom would actually build from this
new location, and it doesn't.
In a couple places I've added a `../` so that the paths point to the repo root
again, so the build actually works now. Sorry for not checking this before.
=> KEYCLOAK-7193 Correct base path in product build pom

product/prod-arguments.json
Commit a6c86176 removed nsp, so deleting it for the product is no longer
required. The associated command has to be removed however, otherwise PME
errors out in PNC.
=> KEYCLOAK-7684 Remove scripts.prepublish delete command from PME jsonUpdate

product/pom.xml
Missed this in the fix for KEYCLOAK-7684, same thing but the pom. I've actually
tried a local build this time, and it works, so this should be the last fix.
=> KEYCLOAK-7711 Remove nsp from product build pom

middleware/auth-utils/grant-manager.js, test/grant-manager-spec.js
While validateGrant, a refresh_token may be validated
as access_token (easy to do with bearer-only api)
This fix add a type checking on attribute 'typ' on the token.
Three kinds of token can be validated:
- Bearer: access_token
- Refresh: refresh_token
- ID: id_token
=> Fix incomplet token validation

middleware/post-auth.js
The `next` callback was not being passed in this instance of `keycloak.accessDenied` (as opposed to the similar call on L27). This means that implementations cannot easily handle the error using standard express error handling mechanisms.
=> [KEYCLOAK-8075] Pass `next` to `accessDenied` method to allow error handling

middleware/enforcer.js, test/fixtures/node-console/index.js, test/keycloak-connect-rest-enforcer-spec.js
Permissions fetched from the server by the enforcer might want to be
used by other middleware in express for futher processing e.g
filtering.
=> [KEYCLOAK-8640] Expose granted permissions to other middleware

middleware/auth-utils/grant-manager.js, test/keycloak-connect-rest-enforcer-spec.js
Fixed a bug related to calling enforce without Authorization header.
The enforce function now also correctly returns a promise to the
calling function in the case of no Authorization header.
=> [KEYCLOAK-8663] RTE in enforce when no Auth header

index.js, middleware/auth-utils/grant-manager.js, middleware/auth-utils/rotation.js, middleware/enforcer.js, package-lock.json, package.json, scripts/start-server.sh, test/fixtures/node-console/index.js, test/grant-manager-spec.js, test/keycloak-connect-rest-spec.js, test/keycloak-connect-web-spec.js, test/unit/hconfig-test.js, test/unit/keycloak-object-test.js, test/utils/webdriver.js
@hmlnarik @stianst after your approval on this, I'm going to update the prod repo. Here some considerations:
* There were two dependencies which required some upgrades Semistandard and Istanbul. `Semistandard` is used to scan for bad practices into the code and also code formatting, while `Istanbul` is used for code coverage.
* After the upgrade `Semistandard` reported several bad smells into our codebase, including formatting and error handling. Both were fixed. That's the reason why this PR touches 14 files.
* Istanbul was deprecated and moved to `nyc` project
* For semistandard there are still some issues reported with npm audit. To make sure that the versions are locked and we're using the most up to date dependencies a new `package-lock.json` file was generated.
* You can see that …
=> KEYCLOAK-9820

CONTRIBUTING.md, index.js, middleware/check-sso.js, middleware/post-auth.js, scripts/stop-server.sh, test/fixtures/node-console/index.js, test/keycloak-connect-web-spec.js
A check SSO will only authenticate the client if the user is already
logged-in, if the user is not logged-in the browser will be redirected
back to the originally-requested URL and remain unauthenticated.
Fix CONTRIBUTING file:
- Fix wrong start server script path;
- Add a missing stop server script.
=>  [KEYCLOAK-10043] Support check-sso option in the Node.js adapter

package.json, product/pom.xml
This removes chromedriver from product's build and move chromedriver to optionalDependencies to be able to pass build in PNC but with same behavior for upstream builds.
=> KEYCLOAK-11281 Remove chromedriver from product's builds

package-lock.json, package.json
* Integration tests for the Node.js adapter are failing due to chromedriver. We need to upgrade its dependencies, in order to make the build pass again.
* Builds green on Travis
* Integration tests failing on Travis when pull-requests are submitted: https://travis-ci.org/keycloak/keycloak-nodejs-connect
1. Clone the Node.js adapter repository
2. Run `make`
=> [KEYCLOAK-11978] Integration tests failing for the Node.js adapter

example/nodejs-example-realm.json
1. Try to import the realm file inside `examples/` to the Keycloak server
1. Run the app inside `examples/` and check if nothing was broken
=> [KEYCLOAK-12482] Keycloak Node.js Adapter example realm file cannot be imported

product/prod-arguments.json
This resolves a problem with the new version of PME, which fails the build when
these old properties are present.
=> KEYCLOAK-15813 Replace dependencyExclusion with dependencyOverride in prod-arguments

stores/cookie-store.js
Hi,
The current keycloak-connect code assumed it could access the keycloak cookie using `request.session[CookieStore.TOKEN_KEY]`, probably with a particular setup of express-session. It causes a redirect loop on login because the code can never access the cookie [related issue](https://stackoverflow.com/questions/59680056/how-to-set-up-node-js-server-with-cookie-based-keycloak-authentication-getting)
Note: The cookie store stores the tokens in the browser unencrypted. There should be a better way to do it? maybe expressjs/cookie-session? 
The following change can be tested with:
```
var express = require('express');
var path = require('path');
var Keycloak = require('keycloak-connect');
var morgan = require('morgan');
var cookieParser = require('cookie-parser');
var session = …
```
=> KEYCLOAK-15441 Fix cookie-store

.github/workflows/ci.yml
https://issues.redhat.com/browse/KEYCLOAK-18141
The current NodeJS release page as of 18-May-2021 (https://nodejs.org/en/about/releases/) indicates the following:
Release  | Status                | Codename | Initial Release | Active LTS Start | Maintenance LTS Start | End-of-life
--------+-----------------+-----------+--------------+----------------+-----------------------+-------------
v12      | Maintenance LTS | Erbium       |  2019-04-23  |    2019-10-21  |    2020-11-30         | 2022-04-30
v14      | Active LTS            | Fermium    |  2020-04-21  |    2020-10-27  |    2021-10-19         | 2023-04-30
v15      | Current               |                   |  2020-10-20  |                         |    2021-04-01         | 2021-06-01
v16      | Current               | …
=> Updated as per KEYCLOAK-18141

.npmignore
We're already using the 'files' field in the package to explicitly include the files in the final package, so this file can be removed.
=> Remove .npmignore in favor of 'files' field

scripts/start-server.sh
The CI breaks on the Quarkus version so let's use the legacy version for now.
=> Use legacy version of Keycloak for testing

scripts/start-server.mjs
Allows the Keycloak server to start on older versions of Node.js (specifically 14).
=> Use promisify() for older versions of Node.js

.github/workflows/main.yml, docs/tests-development.md, package.json
The Keycloak server will keep running even when importing the test realm. This means this no longer needs to be a separate step.
=> Remove extra step when running test server

README.md
Removes the status badges that are no longer updated from the README. Previously these were updated by Travis CI, but that changed when we moved to Github Actions.
These badges are not really essential, so we can simply remove them entirely.
=> Remove status badges that are no longer updated

README.md
Adds the same deprecation message we've added to the NPM page to the README. This is to avoid folks from getting invested in this library, not knowing of our future plans to remove it.
=> Add a deprecation message to the README

scripts/start-server.mjs
Changes the default version string from `999-SNAPSHOT` to `999.0.0-SNAPSHOT`. This makes it a valid version under the [Semantic Versioning](https://semver.org/) standard.
The motivation for this change is to make versioning interoperable between Maven and NPM, as the latter only allows for Semantic Versioning. This allows for simplification in the release process, as we no longer need to convert version numbers from one to the other.
For more information see https://github.com/keycloak/keycloak/issues/17335.
=> Use a valid SemVer format for the SNAPSHOT version

.github/workflows/main.yml, package-lock.json, package.json, scripts/start-server.mjs
closes #522 
PR fixes CI. Summary of the changes:
- Removed property `-Dkeycloak.profile.feature.account2=disabled` . This property is not used for anything in latest Keycloak nightly build as latest Keycloak supports just account3
- Removed environment variables `KEYCLOAK_ADMIN` and `KEYCLOAK_ADMIN_PASSWORD` when starting the server. The variables are not needed as admin user is present anyway in the realm JSON file `test/fixtures/auth-utils/nodejs-test-realm.json`, which is used when importing the JSON file. When those environment variables are used, server fails to start due the DB constraint as there is an attempt to create admin user twice (I guess this check was not present in previous Keycloak server versions and hence it worked)
- Updated Java to 21 for starting the server
- …
=> Fix CI build

.github/workflows/x-release.yml, guides/guides.mjs
Closes #551
Just running the `npm run guides` and uploading the resulting artifact to the GH release.
=> Upload documentation zip to the GitHub release

.github/workflows/main.yml, guides/securing-apps/nodejs-adapter.adoc, package-lock.json, package.json
=> Drop support for end-of-life versions of Node.js

keycloak.d.ts, keycloak.js
Typo fixed from word arrat to array in below files
- keycloak.js
- keycloak.d.ts
=> keycloak.js typo fixed
